# Generated by Django 4.1.1 on 2022-09-18 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='retervails',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='retervails_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
