# Generated by Django 4.1.1 on 2022-09-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productdetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='retervails',
            field=models.IntegerField(default=0),
        ),
    ]
